create or replace TABLE DATAINGESTION.PUBLIC.DATAINGESTION_AUDIT (
	PROCESS_NAME VARCHAR(20),
	FILE_NAME VARCHAR(200),
	LOAD_TIMESTAMP TIMESTAMP_NTZ(9),
	FILE_ROW_COUNT NUMBER(38,0),
	STAGE_ROW_COUNT NUMBER(38,0),
	CORE_ROW_COUNT NUMBER(38,0),
	CORE_BATCH_SK NUMBER(38,0)
);
